spring:
  redis:
#    cluster:
      # 集群部署方式，启动时这里要配置集群中所有master节点
#      nodes: 127.0.0.1:30401,127.0.0.1:30402,127.0.0.1:30403
    host: 127.0.0.1 #192.168.0.129
    port: 6379
    database: 1
    timeout: 3000s
    lettuce:
      pool:
        max-active: -1  #最大活跃连接数，为-1时表示不限制
        max-idle: 50    #最大空闲数
        max-wait: -1    #等待可用连接的最大时间，-1为不限制
        min-idle: 0     #最小空闲数
#    password: 12345678
